### ISSUE TITLE
THe Readme should to be converted...

### ISSUE THREAD

**Issue by StingyJack** [google/google-api-dotnet-client-samples#12]
... so folks dont have to sort through the html tag noise.

**Comment by ProfessorTom** [comment]
I can take a whack at this this evening.

Does anyone know why there is a `README.html`? Should I drop in a `README.md` so there are two README files or should `README.html` be deleted?

**Comment by grant** [comment]
FYI @jskeet @google/yoshi-dotnet.

**Comment by jskeet** [comment]
I'm closing this issue as we're archiving the repository.

**Comment by mikemeinz** [comment]
If you are archiving this repository, will the ResumableUpload.**.Sample programs be placed in another repository so that they are still available as examples?

**Comment by jskeet** [comment]
Yes, I'm working out where to put those. I believe they're only linked to from the YouTube API docs, which means it may be best to suggest moving them to https://github.com/youtube/api-samples
We need an upload sample in https://developers.google.com/api-client-library/dotnet/guide/media_upload, but that doesn't need to come from here.
