### ISSUE TITLE
RequestError ?

### ISSUE THREAD

**Issue by TylerRobotson** [google/google-api-dotnet-client-samples#13]
Potentially just me, but after installing current packages and pulling this code in, I repeatedly get error (using a valid Cloud services API key):
Google.Apis.Requests.RequestError
Invalid Value [400]
Errors [   Message[Invalid Value] Location[ - ] Reason[invalid] Domain[global]

press any key to continue.

**Comment by jskeet** [comment]
Could you tell us which package and what you mean by "this code"? A short but complete example would make it much easier for us to help you.

**Comment by TylerRobotson** [comment]
Apologies! I thought issues were separated by packages.   I was trying to implement the sample package at
google-api-dotnet-client-samples/Translate.TranslateText/   pulled the package and running in Visual Studio 2017. No modifications, other than after the posted error, trying a different ApplicationName.


I was able to use my issued API with https://github.com/Genbox/GoogleTranslate.Net but prefered the method outlined in this sample and wished to use it as a starting point for translation services. Thank you!

**Comment by jskeet** [comment]
Okay, I'll have a look when I can, but I'm currently at a conference so may be slightly delayed.

Note that we now have (in beta) a simpler package to use: [Google.Cloud.Translation.V2](https://www.nuget.org/packages/Google.Cloud.Translation.V2/1.0.0-beta01). It uses the same underlying package, but wraps things up a bit more simply.

What language and text did you request?

**Comment by TylerRobotson** [comment]
Understandable and appreciated - language was "sp", text was "Rock and Roll"   - I'll check out the beta thanks; simpler better.

**Comment by jskeet** [comment]
Okay, that explains it - "sp" isn't a supported language code. See https://cloud.google.com/translate/docs/languages - and in the Google.Cloud.Translation.V2 API you can use the `LanguageCodes` class so you don't need to remember the codes.

**Comment by TylerRobotson** [comment]
EXTREMELY SORRY - I had a list of codes and I have no idea where I had 'sp' from. Thank you
