### ISSUE TITLE
Could someone please post a working code for using servcie account for sending mail?

### ISSUE THREAD

**Issue by AnujaUR** [google/google-api-dotnet-client-samples#14]
I have used the below code, which i got, but gives the error as "Error:\"invalid_client\", Description:\"The OAuth client was not found.\", Uri:\"\""
public GmailService CreateGmailService1()
        {
            String serviceAccountEmail = "Test";           
            var certificate = new X509Certificate2(@"key.p12", "notasecret", X509KeyStorageFlags.Exportable);
            string userEmail = "testaccount";

            ServiceAccountCredential credential = new ServiceAccountCredential(
                new ServiceAccountCredential.Initializer(serviceAccountEmail)
                {
                    User = userEmail,                   
                    Scopes = new[] { "https://www.googleapis.com/auth/gmail.send" }

                }.FromCertificate(certificate)
            );

            var service = new GmailService(new BaseClientService.Initializer()
            {
                HttpClientInitializer = credential,
                ApplicationName = ApplicationName,
            });

**Comment by LindaLawton** [comment]
[ServiceAccount.cs](https://github.com/LindaLawton/Google-Dotnet-Samples/blob/master/Gmail%20API/v1/ServiceAccount.cs)  

Note this will only work with a Gsuite account which has [Domain-Wide Delegation](https://developers.google.com/admin-sdk/reports/v1/guides/delegation) setup for the service account. 


You can not use a serivce account with normal user gmail accounts.

**Comment by AnujaUR** [comment]
Thanks for that, so while using the send, should we be providing the service account email id?
    service.Users.Messages.Send(message,**sFrom**).Execute();

**Comment by LindaLawton** [comment]
You will want to use the email address of the user who you are impersonating.  A service account cant send emails on its own its not a true email address.    (I dont think it may be fun to try though)

**Comment by AnujaUR** [comment]
"Error:\"invalid_client\", Description:\"The OAuth client was not found.\", Uri:\"\""
It errors out as the above messgae?

**Comment by LindaLawton** [comment]
Check your service account settings in Google Developer console. Invalid client means its not set up correctly make sure you are creating service account credentials and downloading the file for it

**Comment by ognyandim** [comment]
What a vague error message! I have lost several hours before finding this. Goodness! Lets someone make this API work as expected! This is supposed to be a classy Googles API! 

[Here](https://developers.google.com/api-client-library/dotnet/guide/aaa_oauth#serviceaccountcredential) in the docs nobody mentions that you have to make it with G Suite account!
  
After trying it with the programatically created email the error changes to : 

>  Message[The caller does not have permission] Location[ - ] Reason[forbidden] Domain[global]

but it should warn that this account is not G suite account.

**Comment by LindaLawton** [comment]
Not all service accounts need to be authorized using a G suite account.   I could make one and grant it access to my personal google drive account if i wanted to.    You only need to grant it access to G suite if you want it to be able to access gsuite.  


That being said @chrisdunelm it might not be a bad idea to edit that page to included something along the lines of Perform [Google Apps domain-wide delegation of authority](https://developers.google.com/+/domains/authentication/delegation)

**Comment by jskeet** [comment]
I'm closing this issue as we're archiving the repository.
