### ISSUE TITLE
Update YouTube Video Titles

### ISSUE THREAD

**Issue by Searchlight-Admin** [google/google-api-dotnet-client-samples#16]
Thanks for these excellent samples.

I am trying to write a .Net VB program to handle various YouTube functions.

One of the things that I am trying to do is update/modify/change the Title of videos that are already on my channel. I don't seem to find the code to do that task. (Which I am guessing is quite simple, but I can quite get it.)

Do you have code that will show the process to update/modify/change a video title?

Thanks for your assistance. God bless you.

**Comment by mikemeinz** [comment]
A bit of VB code to demonstrate changing a video title.
Assumes that **objVideo** contains a YouTube Video object.

`Try`
`    objVideo.Snippet.Title = "New Video Title"`
`    Dim objUpdateRequest As New VideosResource.UpdateRequest(objYouTubeService, objVideo, "id,snippet")`
`    objUpdateRequest.Execute`
`Catch ex As Exception`
`    MsgBox(ex.Message, MsgBoxStyle.Critical, "UpdateRequest")`
`End Try`

**Comment by Searchlight-Admin** [comment]
I sure appreciate your sample code the changing the title. I am a bit new at this and I wonder if you could give me an example of creating that objVideo that contains a YouTube Video object.

**Comment by mikemeinz** [comment]
This example shows how to retrieve Video objects using a list of one or more VideoIds. 

```
Dim strVideoId as string = "Your Video ID" ' Can be one VideoID or several delimited by a comma character
Dim objListRequest As VideosResource.ListRequest
Dim objVideoListResponse As VideoListResponse = Nothing
Dim bOK As Boolean
Try
	bOK = False
	objListRequest = New VideosResource.ListRequest(objYouTubeService, "id,snippet") With {.Id = strVideoIds.ToString}
	objVideoListResponse = objListRequest.Execute
	bOK = True
Catch ex As Exception
        MsgBox(ex.Message, MsgBoxStyle.Critical, "ListRequest")
End Try
If bOK Then
	For Each objVideo As Video In objVideoListResponse.Items
	Try 
		 objVideo.Snippet.Title = "New Video Title" 
		 Dim objUpdateRequest As New VideosResource.UpdateRequest(objYouTubeService, objVideo, "id,snippet") 
		 objUpdateRequest.Execute 
	Catch ex As Exception 
		 MsgBox(ex.Message, MsgBoxStyle.Critical, "UpdateRequest") 
	End Try 
	Next
End If
```

**Comment by Searchlight-Admin** [comment]
Thank you very much.

**Comment by jskeet** [comment]
I'm closing this issue as we're archiving the repository.
