### ISSUE TITLE
What is the redirect URI in Calendar.ASP.NET.MVC5 Sample

### ISSUE THREAD

**Issue by ChuanjenWang** [google/google-api-dotnet-client-samples#17]
When I run the project Calendar.ASP.NET.MVC5, I got "Error: redirect_uri_mismatch". I don't know what is the correct **redirect url** in this project? Cloud someone can give me a suggestion?

By the way, in the Google official instruction, it suggest use **your_site/AuthCallback/IndexAsync** , but obviously, this is not appropriate in this project.
[https://developers.google.com/api-client-library/dotnet/guide/aaa_oauth](url)

**Comment by jskeet** [comment]
I'm closing this issue as we're archiving the repository.
