### ISSUE TITLE
GoogleUserId issue

### ISSUE THREAD

**Issue by skwebies** [google/google-api-dotnet-client-samples#19]
Hi, 

Please clearify that GoogleUserId is email address or just "GoogleUserId", I get error on below lines, because userId becomes null. got an error like this

Key MUST have a value

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.ArgumentException: Key MUST have a value
      
**A Method inside CalendarController**
  
  
**private async Task<UserCredential> GetCredentialForApiAsync()
        {
            var initializer = new GoogleAuthorizationCodeFlow.Initializer
            {
                ClientSecrets = new ClientSecrets
                {
                    ClientId = MyClientSecrets.ClientId,
                    ClientSecret = MyClientSecrets.ClientSecret,

                },
                Scopes = MyRequestedScopes.Scopes,
            };
            var flow = new GoogleAuthorizationCodeFlow(initializer);

            var identity = await HttpContext.GetOwinContext().Authentication.GetExternalIdentityAsync(DefaultAuthenticationTypes.ApplicationCookie);
            var userId = identity.FindFirstValue(MyClaimTypes.GoogleUserId);

            var token = await dataStore.GetAsync<TokenResponse>(userId);

            return new UserCredential(flow, userId, token);
        }**

**Comment by jskeet** [comment]
I'm closing this issue as we're archiving the repository.
