### ISSUE TITLE
How can I get downloadUrl in v3 ?

### ISSUE THREAD

**Issue by asd24862486** [google/google-api-dotnet-client-samples#24]
Hi,I encountered a problem ,because the different from v3 and v2.

I want to get the downloadUrl.
I refer to this document https://developers.google.com/drive/api/v3/migration
but,I don't understand that how to achieve **files.get with ?alt=media** in google drive api v3

**Comment by jskeet** [comment]
(Do we have an easy way of adding arbitrary query parameters, Chris?)

**Comment by ubaidsoomro123** [comment]
> (Do we have an easy way of adding arbitrary query parameters, Chris?)
If you are not understanding the problem by seeing title then why are you here?

**Comment by jskeet** [comment]
I'm closing this issue as we're archiving the repository.
